const { skeleton } = require('@skeletonlabs/skeleton/plugin');
const forms = require('@tailwindcss/forms');
const path = require('path');

/** @type {import('tailwindcss').Config} */
module.exports = {
	darkMode: 'class',
	content: [
		'./src/**/*.{html,js,svelte,ts}',
		path.join(require.resolve('@skeletonlabs/skeleton'), '../**/*.{html,js,svelte,ts}')
	],
	safelist: [
		// Skeleton UI v2 classes spécifiques
		'variant-filled-primary',
		'variant-filled-secondary', 
		'variant-filled-tertiary',
		'variant-filled-success',
		'variant-filled-warning',
		'variant-filled-error',
		'variant-soft-primary',
		'variant-soft-secondary',
		'variant-soft-success',
		'variant-soft-warning',
		'variant-soft-error',
		'variant-soft-surface',
		'variant-outline-primary',
		'variant-ghost-primary',
		'variant-ghost-surface',
		'btn',
		'btn-sm',
		'btn-lg',
		'card',
		'card-header',
		'badge',
		'alert',
		'alert-message',
		'label',
		'input',
		'table',
		'table-hover',
		'table-container',
		'table-cell-fit',
		'rounded-token',
		'rounded-container-token',
		'bg-surface-backdrop-token',
		'bg-surface-50-900-token',
		'bg-surface-100-800-token',
		'bg-surface-200-700-token',
		'text-surface-500',
		'text-surface-600',
		'text-surface-700',
		// Utilitaires Tailwind essentiels
		'flex',
		'items-center',
		'items-start',
		'justify-center',
		'justify-between',
		'justify-end',
		'space-x-2',
		'space-x-3',
		'space-x-4',
		'space-x-6',
		'space-y-2',
		'space-y-3',
		'space-y-4',
		'space-y-6',
		'p-2',
		'p-3',
		'p-4',
		'p-6',
		'p-12',
		'px-2',
		'px-3',
		'px-4',
		'py-1',
		'py-2',
		'py-4',
		'mb-2',
		'mb-4',
		'mb-6',
		'mt-4',
		'mt-6',
		'ml-2',
		'ml-3',
		'ml-4',
		'mr-2',
		'mr-3',
		'grid',
		'grid-cols-1',
		'md:grid-cols-3',
		'md:grid-cols-4',
		'lg:grid-cols-2',
		'gap-4',
		'gap-6',
		'w-full',
		'w-4',
		'w-5',
		'w-6',
		'w-8',
		'w-16',
		'h-full',
		'h-2',
		'h-4',
		'h-5',
		'h-6',
		'h-8',
		'h-16',
		'text-sm',
		'text-base',
		'text-lg',
		'text-xl',
		'text-2xl',
		'font-bold',
		'font-medium',
		'font-mono',
		'uppercase',
		'tracking-wide',
		'tracking-widest',
		'text-center',
		'cursor-pointer',
		'animate-spin',
		'rounded-full',
		'bg-primary-500',
		'bg-secondary-500',
		'bg-success-500',
		'bg-warning-500',
		'bg-error-500',
		'text-primary-500',
		'text-secondary-500',
		'text-success-500',
		'text-warning-500',
		'text-error-500',
		'text-white',
		'backdrop-blur-sm',
		'fixed',
		'inset-0',
		'z-[999]',
		'max-w-md',
		'max-w-xs',
		'max-h-32',
		'min-w-32',
		'mx-auto',
		'mx-4',
		'overflow-auto',
		'whitespace-pre-wrap',
		'border-t',
		'border-surface-400',
		'lg:hidden',
		'sm:flex-row',
		'sm:items-center',
		'sm:justify-between',
		'sm:mt-0',
		'container'
	],
	theme: {
		extend: {},
	},
	plugins: [
		forms,
		skeleton({
			themes: {
				preset: [ "skeleton", "wintry", "modern" ]
			}
		})
	],
};
