# docker-compose.yml
services:
  redriva:
    image: ghcr.io/kesurof/redriva:latest
    container_name: redriva
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    env_file:
      - ./config/.env
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3