services:
  redriva:
    build: .
    # image: ghcr.io/kesurof/redriva:latest  # Décommentez pour utiliser l'image pré-construite
    container_name: redriva
    restart: unless-stopped
    
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Paris}
    
    env_file:
      - .env
    
    ports:
      - "${PORT:-5000}:5000"
    
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - /etc/localtime:/etc/localtime:ro
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Configuration optionnelle pour développement
  # redriva-dev:
  #   extends: redriva
  #   volumes:
  #     - ./src:/app/src:ro
  #     - ./data:/app/data
  #   environment:
  #     - FLASK_DEBUG=1
  #   command: ["python", "src/web.py", "--debug"]
