# Configuration SSDV2 pour Redriva
# À ajouter dans votre docker-compose.yml SSDV2

services:
  redriva:
    image: kesurof/redriva:ssdv2
    container_name: redriva
    restart: unless-stopped
    
    # Variables d'environnement SSDV2
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Paris}
      - RD_TOKEN=${RD_TOKEN}
      
    # Ports
    ports:
      - "5000:5000"
      
    # Volumes pour persistance
    volumes:
      - ./data/redriva:/app/data
      - ./medias:/app/medias
      - /etc/localtime:/etc/localtime:ro
      
    # Santé du container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
    # Labels SSDV2
    labels:
      - "ssdv2.enable=true"
      - "ssdv2.category=media"
      - "ssdv2.subcategory=downloader"
      - "ssdv2.name=Redriva"
      - "ssdv2.description=Gestionnaire Real-Debrid"
      - "ssdv2.icon=https://real-debrid.com/favicon.ico"
      - "ssdv2.port=5000"
      - "ssdv2.protocol=http"
      - "traefik.enable=true"
      - "traefik.http.routers.redriva.rule=Host(\`redriva.${DOMAIN}\`)"
      - "traefik.http.routers.redriva.entrypoints=websecure"
      - "traefik.http.routers.redriva.tls.certresolver=letsencrypt"
      - "traefik.http.services.redriva.loadbalancer.server.port=5000"
