version: '3.8'

services:
  redriva:
    image: ghcr.io/kesurof/redriva:ssdv2
    container_name: redriva
    restart: unless-stopped
    
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Paris}
    
    ports:
      - "5000:5000"
    
    volumes:
      - ./config:/app/config:rw
      - ./data:/app/data:rw
      - ${HOME}/scripts/zurg/data/info:/zurg/data/info:ro
      - ${HOME}/Medias:/app/medias:rw
      - ${HOME}:${HOME}
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro