# .github/workflows/docker-publish.yml

name: Build and Push Docker Image

# Ce workflow se déclenche à chaque push sur la branche "main"
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    # Utilise la dernière version d'Ubuntu comme environnement d'exécution
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère le code de votre dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Se connecte à Docker Hub en utilisant les secrets configurés
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Met en place Docker Buildx pour des builds optimisés
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Construit l'image et la pousse sur Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # Pousse l'image vers le registre
          push: true
          # Crée deux tags pour l'image : "latest" et un tag basé sur le hash du commit
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/redriva:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/redriva:${{ github.sha }}